### ISSUE TITLE
How to run micro-test?

### ISSUE THREAD

**Issue by LiYuTingxxn** [dmemsys/FUSEE#1]
Hello, I am interested in FUSEE which is an admirable work! Recently I tried to run the source code, but met some erros and hope to get your help. My experimental environment was 3 servers with Mellanox-CX5 RNIC, using the ROCE v2 protocol; Two serve as Memory Nodes and one serves as Compute Node.
server 1's server_config is placed in /FUSEE/build/ directory, and discribled as follows:
{
	    "role": "SERVER",
	    "conn_type": "ENS7F1",
	    "server_id": 0,
	    "udp_port": 2333,
	    "memory_num": 2,
	    "memory_ips": [
	        "192.168.0.1"]
	    ],
	    "ib_dev_id": 1,
	    "ib_port_id": 1,
	    "ib_gid_idx": 0,
	
	    "server_base_addr":  "0x10000000",
	    "server_data_len":   15032385536,
	    "block_size":        67108864,
	    "subblock_size":     256,
	    "client_local_size": 1073741824,
	
	    "num_replication": 2,
	
	    "main_core_id": 0,
	    "poll_core_id": 1,
	    "bg_core_id": 2,
	    "gc_core_id": 3
        }
server 2's server_config is placed in /FUSEE/build/ directory, and discribled as follows:
{
		    "role": "SERVER",
		    "conn_type": "ENS7F1",
		    "server_id":1,
		    "udp_port": 2333,
		    "memory_num": 2,
		    "memory_ips": [
		        "192.168.0.2"]
		    ],
		    "ib_dev_id": 1,
		    "ib_port_id": 1,
		    "ib_gid_idx": 0,
		
		    "server_base_addr":  "0x10000000",
		    "server_data_len":   15032385536,
		    "block_size":        67108864,
		    "subblock_size":     256,
		    "client_local_size": 1073741824,
		
		    "num_replication": 2,
		
		    "main_core_id": 0,
		    "poll_core_id": 1,
		    "bg_core_id": 2,
		    "gc_core_id": 3
        }
server 3 as Compute node, and Client_config.json is placed in /FUSEE/build/ directory, and discribled as follows:
{
		    "role": "CLIENT",
		    "conn_type": "ENS7F1",
		    "server_id": 0,
		    "udp_port": 2333,
		    "memory_num": 2,
		    "memory_ips": [
		        "192.168.0.1",
		        "192.168.0.2"
		    ],
		    "ib_dev_id": 1,
		    "ib_port_id": 1,
		    "ib_gid_idx": 0,
		
		    "server_base_addr":  "0x10000000",
		    "server_data_len":   15032385536,
		    "block_size":        67108864,
		    "subblock_size":     256,
		    "client_local_size": 1073741824,
		
		    "num_replication": 2,
			"num_idx_rep": 1,
		    "num_coroutines": 10,
		    "miss_rate_threash": 0.1,
		    "workload_run_time": 10,
		    "micro_workload_num": 10000,
		    
		    "main_core_id": 0,
		    "poll_core_id": 1,
		    "bg_core_id": 2,
		    "gc_core_id": 3
        }
 Firstly, I run memory node as READme.md at server 1:
 cd /FUSEE-master/build# numactl -N 0 -m 0 ./ycsb-test/ycsb_test_server 0
		===== Starting Server 0 ====
		kv_area_addr: 18000000, block_size: 4000000
		my_sid_: 0, num_memory_:2
		num_rep_blocks: 26, num_blovks: 26, limit: 90000000
		press to exit 
		==== Ending Server 0 ====

Secondly,  I run memory node as READme.md at server 2:
cd /FUSEE-master/build# numactl -N 0 -m 0 ./ycsb-test/ycsb_test_server 1
		===== Starting Server 1 ====
		kv_area_addr: 18000000, block_size: 4000000
		my_sid_: 1, num_memory_:2
		num_rep_blocks: 26, num_blovks: 26, limit: 90000000
		press to exit 
		==== Ending Server 1 ====

Thirdly, I run compute node as READme.md at server 3:
cd /FUSEE-master/build/micro-test# numactl -N 0 -m 0 ./lantency_test_client ../client_config.json
	   main process running on core: 0
	   server_kv_area_addr: 28000000 26
	   num_rep_blocks: 26
	   Cannot have allocated 28000001
The error is " Cannot have allocated 28000001"
So, how to solve it? Could you tell me what each parameter in the servr_config.json and client_cofig.json is used for?  Thank you very much!

**Comment by bernardshen** [comment]
Hi, the conn_type should be either IB or ROCE. It depends on the lower-level protocol you use.

**Comment by LiYuTingxxn** [comment]
非常感谢你的回复！按照建议和回复我修改为ROCE的配置，运行latency测试，遇到了一些问题，希望得到你的帮助。
1：client端卡在ClientMM::init_reg_space函数中“ret = nm->nm_rdma_write_inl_to_sid(&meta_info, sizeof(ClientMetaAddrInfo),client_meta_addr_, rkey, i);”ibv_post_send函数ret返回值为22， 表示RDMA WRITE post失败，已经检查在此之前完成了REQ_CONNECT消息交互，建立了RDMA连接，也完成了REQ_ALLOC消息交互,交换了内存metadata。QP信息也能正确得到，请问post提交不了可能是什么问题呢？
2：是不是micro_test和ycsb test的server端共用micro-test中的ycsb_test_server？（如redme中给的例子显示）
