### ISSUE TITLE
How to know the next pointer when using slab allocation?

### ISSUE THREAD

**Issue by fangneverdown** [dmemsys/FUSEE#3]
![image](https://github.com/dmemsys/FUSEE/assets/34860307/e1baa302-c293-48f7-907e-a2bdcd868c35)
The local allocation should fit the size class. Different size classes have different freeLists.  when allocating block 'a', we don't know the next allocation size ,thus don't know the pointer pointing to the header of freelist which fit next allocation size.

**Comment by bernardshen** [comment]
As mentioned in the paper, a linked list is maintained for each size class.
