### ISSUE TITLE
Does the FUSEE code contains SPLIT operaion?

### ISSUE THREAD

**Issue by sunce4t** [dmemsys/FUSEE#4]
As I know, RACE has implemented SPLIT OPERATION to support extendible hashing, however, i find the SEARCH, UPDATE, INSERT, DELETE operation in FUSEE code except SPLIT.
I read it for a long time and still haven't found it, so hope to get your answer, thank you very much!

**Comment by bernardshen** [comment]
No, we did not implement SPLIT in the current implementation.

**Comment by sunce4t** [comment]
> No, we did not implement SPLIT in the current implementation.

thanks !
